### ISSUE TITLE
Generate my own "model3Ddlib.mat"

### ISSUE THREAD

**Issue by SJHNJU** [dougsouza/face-frontalization#24]
How can I generate my own "model3Ddlib.mat", if I want use my own template 3D model?

Is there a way or tool that I can use? 

Thank you!

**Comment by SJHNJU** [comment]
After two days work, I successfully replace the original template face point cloud and use the point cloud of my own to generate front view of my face picture.

**Comment by XWalways** [comment]
> After two days work, I successfully replace the original template face point cloud and use the point cloud of my own to generate front view of my face picture.

Hello，how to generate the model3Ddlib.mat based on my own face data， thx
