### ISSUE TITLE
Try demo with other facial feature detector

### ISSUE THREAD

**Issue by xiehao-ai** [dougsouza/face-frontalization#29]
Thank you for this work. 
I tried demo.py with the other facial feature detector and got the landmarks. 
I wonder if the model3Ddlib.mat needs to be modified?

Thanks,
Xie

**Comment by dougsouza** [comment]
Hi @kszlk, it the model3D needs to be updated. Since the 3D model consists of the same landmarks detected on a 3D face, you would need to generate a new one for your landmark detector.

Please refer to the project page for how to do it: https://talhassner.github.io/home/publication/2015_CVPR_1

**Comment by xiehao-ai** [comment]
Thanks for your reply!
